import { sql } from 'drizzle-orm';
import { db } from './db';

export type ProvenanceCount = {
  imported: number;
  ai: number;
  human: number;
};

export type SiteStats = {
  packages: { total: number; canonicals: number };
  ratings: ProvenanceCount;
  /* translations:
   * - `packagesWith*`: count of DISTINCT packages that have at least one
   *   description in some locale. This is the honest "how many packages
   *   carry translated metadata" number.
   * - `rowsBy*`: raw (package × locale) row count. Useful for transparency
   *   but inflated for a casual reader since AppStream metainfo typically
   *   ships 5-50 locales bundled in a single upstream file.
   */
  translations: {
    packagesWithImported: number;
    packagesWithAi: number;
    packagesWithHuman: number;
    rowsImported: number;
    rowsAi: number;
    rowsHuman: number;
    avgLocalesPerPackage: number;
    distinctLocales: number;
  };
  embeddings: { total: number };
  reviewers: { registered: number; active90d: number };
  disputes: { open: number };
};

let cache: { value: SiteStats; expiresAt: number } | null = null;
const TTL_MS = 60_000;

/* Returns counts split by provenance — imported (from upstream feeds),
 * ai (generated by our classifier/translator workers), human (reviewed/created
 * by a logged-in reviewer). Showing only the sum is misleading: most rows
 * are upstream redistribution, not work this project did. */
export async function getSiteStats(): Promise<SiteStats> {
  if (cache && cache.expiresAt > Date.now()) return cache.value;
  const rows = await db.execute<{
    pkg_total: number; pkg_canonicals: number;
    rat_imported: number; rat_ai: number; rat_human: number;
    tr_pkg_imp: number; tr_pkg_ai: number; tr_pkg_hum: number;
    tr_rows_imp: number; tr_rows_ai: number; tr_rows_hum: number;
    tr_locales: number;
    emb_total: number;
    rev_registered: number; rev_active90d: number;
    dispute_open: number;
  }>(sql`
    SELECT
      (SELECT COUNT(*)::int FROM package)                                                                                                       AS pkg_total,
      (SELECT COUNT(DISTINCT COALESCE(canonical_slug, slug))::int FROM package)                                                                 AS pkg_canonicals,
      (SELECT COUNT(*)::int FROM rating_current WHERE dominant_source = 'oars_official')                                                        AS rat_imported,
      (SELECT COUNT(*)::int FROM rating_current WHERE dominant_source LIKE 'ai_%')                                                              AS rat_ai,
      (SELECT COUNT(*)::int FROM rating_current WHERE dominant_source = 'human_reviewer')                                                       AS rat_human,
      (SELECT COUNT(DISTINCT package_id)::int FROM package_translation WHERE translated_by = 'upstream')                                        AS tr_pkg_imp,
      (SELECT COUNT(DISTINCT package_id)::int FROM package_translation WHERE translated_by LIKE 'ai_%')                                         AS tr_pkg_ai,
      (SELECT COUNT(DISTINCT package_id)::int FROM package_translation WHERE status IN ('reviewed','official') AND translated_by NOT IN ('upstream') AND translated_by NOT LIKE 'ai_%') AS tr_pkg_hum,
      (SELECT COUNT(*)::int FROM package_translation WHERE translated_by = 'upstream')                                                          AS tr_rows_imp,
      (SELECT COUNT(*)::int FROM package_translation WHERE translated_by LIKE 'ai_%')                                                           AS tr_rows_ai,
      (SELECT COUNT(*)::int FROM package_translation WHERE status IN ('reviewed','official') AND translated_by NOT IN ('upstream') AND translated_by NOT LIKE 'ai_%') AS tr_rows_hum,
      (SELECT COUNT(DISTINCT locale)::int FROM package_translation)                                                                             AS tr_locales,
      (SELECT COUNT(*)::int FROM package_embedding)                                                                                             AS emb_total,
      (SELECT COUNT(*)::int FROM "user" WHERE role IN ('reviewer','translator'))                                                                AS rev_registered,
      (SELECT COUNT(DISTINCT resolved_by)::int FROM dispute
        WHERE resolved_at > NOW() - INTERVAL '90 days' AND resolved_by IS NOT NULL)                                                             AS rev_active90d,
      (SELECT COUNT(*)::int FROM dispute WHERE status IN ('open','reviewing'))                                                                  AS dispute_open
  `);
  const r = rows[0] ?? {
    pkg_total: 0, pkg_canonicals: 0,
    rat_imported: 0, rat_ai: 0, rat_human: 0,
    tr_pkg_imp: 0, tr_pkg_ai: 0, tr_pkg_hum: 0,
    tr_rows_imp: 0, tr_rows_ai: 0, tr_rows_hum: 0,
    tr_locales: 0,
    emb_total: 0, rev_registered: 0, rev_active90d: 0, dispute_open: 0,
  };
  const totalRows = r.tr_rows_imp + r.tr_rows_ai + r.tr_rows_hum;
  const totalPkgsWithTr = r.tr_pkg_imp + r.tr_pkg_ai + r.tr_pkg_hum;
  const avgLocales = totalPkgsWithTr > 0 ? Math.round((totalRows / totalPkgsWithTr) * 10) / 10 : 0;
  const value: SiteStats = {
    packages: { total: r.pkg_total, canonicals: r.pkg_canonicals },
    ratings: { imported: r.rat_imported, ai: r.rat_ai, human: r.rat_human },
    translations: {
      packagesWithImported: r.tr_pkg_imp,
      packagesWithAi:       r.tr_pkg_ai,
      packagesWithHuman:    r.tr_pkg_hum,
      rowsImported:         r.tr_rows_imp,
      rowsAi:               r.tr_rows_ai,
      rowsHuman:            r.tr_rows_hum,
      avgLocalesPerPackage: avgLocales,
      distinctLocales:      r.tr_locales,
    },
    embeddings: { total: r.emb_total },
    reviewers: { registered: r.rev_registered, active90d: r.rev_active90d },
    disputes: { open: r.dispute_open },
  };
  cache = { value, expiresAt: Date.now() + TTL_MS };
  return value;
}

/* ---------- Curation cockpit stats (admin dashboard) ----------
 * Decision-useful panels for the review backlog: status totals + burn-down,
 * per-locale coverage gaps, worker health, dispute hotspots, reviewer activity,
 * and a couple of cheap data-quality signals. 60s cache. */
export type CurationStats = {
  backlog: { draft: number; reviewed: number; official: number };
  coverageByLocale: Array<{ locale: string; draft: number; reviewed: number; official: number }>;
  workers: {
    runningNow: number;
    runs24h: number;
    errors24h: number;
    perWorker: Array<{
      worker: string; status: string; startedAt: string | null; finishedAt: string | null;
      itemsProcessed: number; errorsCount: number;
    }>;
  };
  disputes: { open: number; hotspots: Array<{ packageId: number; name: string; n: number }> };
  burnDown: Array<{ day: string; reviewed: number }>;
  reviewers: Array<{ actor: string; n: number }>;
  quality: { aiRatings: number; missingProfile: number; noHumanTranslation: number };
};

let curationCache: { value: CurationStats; expiresAt: number } | null = null;

export async function getCurationStats(): Promise<CurationStats> {
  if (curationCache && curationCache.expiresAt > Date.now()) return curationCache.value;

  const [backlogRows, localeRows, workerAgg, perWorker, disputeAgg, hotspotRows, burnRows, reviewerRows, qualityRow] =
    await Promise.all([
      db.execute<{ status: string; n: number }>(sql`
        SELECT status, COUNT(*)::int AS n FROM package_translation GROUP BY status
      `),
      db.execute<{ locale: string; draft: number; reviewed: number; official: number }>(sql`
        SELECT locale,
          COUNT(*) FILTER (WHERE status = 'draft')::int AS draft,
          COUNT(*) FILTER (WHERE status = 'reviewed')::int AS reviewed,
          COUNT(*) FILTER (WHERE status = 'official')::int AS official
        FROM package_translation
        GROUP BY locale
        ORDER BY draft DESC
        LIMIT 10
      `),
      db.execute<{ running: number; runs24h: number; errors24h: number }>(sql`
        SELECT
          COUNT(*) FILTER (WHERE status = 'running')::int AS running,
          COUNT(*) FILTER (WHERE started_at > NOW() - INTERVAL '24 hours')::int AS runs24h,
          COUNT(*) FILTER (WHERE status = 'error' AND started_at > NOW() - INTERVAL '24 hours')::int AS errors24h
        FROM worker_run
      `),
      db.execute<{
        worker: string; status: string; started_at: string | null; finished_at: string | null;
        items_processed: number; errors_count: number;
      }>(sql`
        SELECT DISTINCT ON (worker)
          worker, status, started_at, finished_at, items_processed, errors_count
        FROM worker_run
        ORDER BY worker, started_at DESC
      `),
      db.execute<{ n: number }>(sql`
        SELECT COUNT(*)::int AS n FROM dispute WHERE status IN ('open','reviewing')
      `),
      db.execute<{ package_id: number; name: string; n: number }>(sql`
        SELECT d.package_id, p.name, COUNT(*)::int AS n
        FROM dispute d JOIN package p ON p.id = d.package_id
        WHERE d.status IN ('open','reviewing')
        GROUP BY d.package_id, p.name
        ORDER BY n DESC
        LIMIT 5
      `),
      db.execute<{ day: string; reviewed: number }>(sql`
        SELECT to_char(date_trunc('day', at), 'YYYY-MM-DD') AS day, COUNT(*)::int AS reviewed
        FROM audit_log
        WHERE action = 'translation_review'
          AND at > NOW() - INTERVAL '14 days'
          AND (after->>'status') IN ('reviewed','official')
        GROUP BY date_trunc('day', at)
        ORDER BY day
      `),
      db.execute<{ actor: string; n: number }>(sql`
        SELECT actor, COUNT(*)::int AS n
        FROM audit_log
        WHERE actor IS NOT NULL
          AND at > NOW() - INTERVAL '7 days'
          AND action LIKE '%review%'
        GROUP BY actor
        ORDER BY n DESC
        LIMIT 8
      `),
      db.execute<{ ai_ratings: number; missing_profile: number; no_human_tr: number }>(sql`
        SELECT
          (SELECT COUNT(*)::int FROM rating_current WHERE dominant_source LIKE 'ai\\_%' ESCAPE '\\') AS ai_ratings,
          (SELECT COUNT(*)::int FROM package p
             LEFT JOIN package_profile pp ON pp.package_id = p.id
             WHERE p.moderation_status = 'approved'
               AND (pp.package_id IS NULL OR pp.component_type = 'unknown')) AS missing_profile,
          (SELECT COUNT(DISTINCT package_id)::int FROM package_translation
             WHERE status = 'draft') AS no_human_tr
      `),
    ]);

  const backlog = { draft: 0, reviewed: 0, official: 0 };
  for (const r of backlogRows as unknown as Array<{ status: string; n: number }>) {
    if (r.status === 'draft') backlog.draft = r.n;
    else if (r.status === 'reviewed') backlog.reviewed = r.n;
    else if (r.status === 'official') backlog.official = r.n;
  }
  const wa = (workerAgg as unknown as Array<{ running: number; runs24h: number; errors24h: number }>)[0]
    ?? { running: 0, runs24h: 0, errors24h: 0 };
  const ql = (qualityRow as unknown as Array<{ ai_ratings: number; missing_profile: number; no_human_tr: number }>)[0]
    ?? { ai_ratings: 0, missing_profile: 0, no_human_tr: 0 };

  const value: CurationStats = {
    backlog,
    coverageByLocale: localeRows as unknown as CurationStats['coverageByLocale'],
    workers: {
      runningNow: wa.running,
      runs24h: wa.runs24h,
      errors24h: wa.errors24h,
      perWorker: (perWorker as unknown as Array<{
        worker: string; status: string; started_at: string | null; finished_at: string | null;
        items_processed: number; errors_count: number;
      }>).map((w) => ({
        worker: w.worker, status: w.status, startedAt: w.started_at, finishedAt: w.finished_at,
        itemsProcessed: w.items_processed, errorsCount: w.errors_count,
      })),
    },
    disputes: {
      open: (disputeAgg as unknown as Array<{ n: number }>)[0]?.n ?? 0,
      hotspots: (hotspotRows as unknown as Array<{ package_id: number; name: string; n: number }>)
        .map((h) => ({ packageId: h.package_id, name: h.name, n: h.n })),
    },
    burnDown: burnRows as unknown as CurationStats['burnDown'],
    reviewers: reviewerRows as unknown as CurationStats['reviewers'],
    quality: { aiRatings: ql.ai_ratings, missingProfile: ql.missing_profile, noHumanTranslation: ql.no_human_tr },
  };
  curationCache = { value, expiresAt: Date.now() + TTL_MS };
  return value;
}

/* ---------- Provenance breakdown (Fase 5 public metrics) ----------
 *
 * Classification rules — chosen after inspecting actual DB values:
 *   - package.source           → manjaro | aur | flathub | debian
 *   - package_translation.translated_by → bucketed as:
 *       imported = ('upstream','flathub_appstream','debian_ddtp','reingest_external')
 *       ai       = LIKE 'ai\_%'    (ai_claude_code, ai_legacy_*, …)
 *       human    = ('human','reviewer','admin') OR status='reviewed'/'official'
 *                  with translated_by NOT in imported/ai buckets.
 *   - rating.source            → bucketed as:
 *       imported = LIKE 'oars_%' OR LIKE 'flathub%' OR LIKE 'upstream%'
 *       ai       = LIKE 'ai\_%'
 *       human    = ('human','reviewer','admin')
 *   - reviewers.active_90d     → DISTINCT actor in audit_log whose action
 *       matches '%review%' OR is a rating/translation mutation in last 90d.
 *       audit_log is currently sparse, so we also surface total_with_role
 *       (user.role IN ('reviewer','admin')) for an honest "people who *could*
 *       review" denominator — the page caption must say so.
 */
export type ProvenanceBreakdown = {
  packages: { total: number; bySource: Record<string, number> };
  translations: {
    total: number;
    byLocale: Record<string, { imported: number; ai: number; human: number }>;
  };
  ratings: { total: number; imported: number; ai: number; human: number };
  embeddings: { total: number };
  reviewers: { active_90d: number; total_with_role: number };
  generated_at: string;
};

let provCache: { value: ProvenanceBreakdown; expiresAt: number } | null = null;
const PROV_TTL_MS = 5 * 60_000;

export async function getProvenanceBreakdown(): Promise<ProvenanceBreakdown> {
  if (provCache && provCache.expiresAt > Date.now()) return provCache.value;

  const [pkgBySource, trByLocale, ratingRow, embRow, reviewersRow] = await Promise.all([
    db.execute<{ source: string; n: number }>(sql`
      SELECT source, COUNT(*)::int AS n FROM package GROUP BY source
    `),
    db.execute<{ locale: string; imported: number; ai: number; human: number }>(sql`
      SELECT
        locale,
        COUNT(*) FILTER (
          WHERE translated_by IN ('upstream','flathub_appstream','debian_ddtp','reingest_external')
        )::int AS imported,
        COUNT(*) FILTER (WHERE translated_by LIKE 'ai\\_%' ESCAPE '\\')::int AS ai,
        COUNT(*) FILTER (
          WHERE translated_by IN ('human','reviewer','admin')
             OR (status IN ('reviewed','official')
                 AND (translated_by IS NULL
                      OR translated_by NOT IN
                         ('upstream','flathub_appstream','debian_ddtp','reingest_external')
                      AND translated_by NOT LIKE 'ai\\_%' ESCAPE '\\'))
        )::int AS human
      FROM package_translation
      GROUP BY locale
      ORDER BY locale
    `),
    db.execute<{ total: number; imported: number; ai: number; human: number }>(sql`
      SELECT
        COUNT(*)::int AS total,
        COUNT(*) FILTER (
          WHERE source LIKE 'oars_%' OR source LIKE 'flathub%' OR source LIKE 'upstream%'
        )::int AS imported,
        COUNT(*) FILTER (WHERE source LIKE 'ai\\_%' ESCAPE '\\')::int AS ai,
        COUNT(*) FILTER (WHERE source IN ('human','reviewer','admin'))::int AS human
      FROM rating
    `),
    db.execute<{ total: number }>(sql`SELECT COUNT(*)::int AS total FROM package_embedding`),
    db.execute<{ active_90d: number; total_with_role: number }>(sql`
      SELECT
        (SELECT COUNT(DISTINCT actor)::int
           FROM audit_log
          WHERE actor IS NOT NULL
            AND at > NOW() - INTERVAL '90 days'
            AND (action LIKE '%review%'
                 OR action IN ('translation_review','rating_override','dispute_status'))
        ) AS active_90d,
        (SELECT COUNT(*)::int FROM "user" WHERE role IN ('reviewer','admin'))
          AS total_with_role
    `),
  ]);

  const bySource: Record<string, number> = {};
  let pkgTotal = 0;
  for (const r of pkgBySource as unknown as Array<{ source: string; n: number }>) {
    bySource[r.source] = r.n;
    pkgTotal += r.n;
  }

  const byLocale: Record<string, { imported: number; ai: number; human: number }> = {};
  let trTotal = 0;
  for (const r of trByLocale as unknown as Array<{
    locale: string; imported: number; ai: number; human: number;
  }>) {
    byLocale[r.locale] = { imported: r.imported, ai: r.ai, human: r.human };
    trTotal += r.imported + r.ai + r.human;
  }

  const rat = (ratingRow as unknown as Array<{
    total: number; imported: number; ai: number; human: number;
  }>)[0] ?? { total: 0, imported: 0, ai: 0, human: 0 };
  const emb = (embRow as unknown as Array<{ total: number }>)[0] ?? { total: 0 };
  const rev = (reviewersRow as unknown as Array<{
    active_90d: number; total_with_role: number;
  }>)[0] ?? { active_90d: 0, total_with_role: 0 };

  const value: ProvenanceBreakdown = {
    packages: { total: pkgTotal, bySource },
    translations: { total: trTotal, byLocale },
    ratings: { total: rat.total, imported: rat.imported, ai: rat.ai, human: rat.human },
    embeddings: { total: emb.total },
    reviewers: { active_90d: rev.active_90d, total_with_role: rev.total_with_role },
    generated_at: new Date().toISOString(),
  };
  provCache = { value, expiresAt: Date.now() + PROV_TTL_MS };
  return value;
}
